### ISSUE TITLE
Npm Start Error

### ISSUE THREAD

**Issue by XBITSwitzerland** [edgraaff/quorum-rpc-proxy#1]
Hello

When I clone your code and do "npm start" I get this error:

```
$ npm start

> rpc-proxy@1.0.0 start C:\Blockchain\quorum\workplace\quorum-rpc-proxy
> node .

C:\Blockchain\quorum\workplace\quorum-rpc-proxy\index.js:7
for (const proxy of config) {
                    ^

TypeError: config is not iterable
    at Object.<anonymous> (C:\Blockchain\quorum\workplace\quorum-rpc-proxy\index.js:7:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpc-proxy@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpc-proxy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dany.vandermeij\AppData\Roaming\npm-cache\_logs\2019-01-22T08_27_42_293Z-debug.log

```

**Comment by edgraaff** [comment]
What's in `config.js`? Is the exported value an array?

**Comment by XBITSwitzerland** [comment]
Hello, I just found the problem, I did:

```
module.exports = {
  rpcUrl: 'http://localhost:22000',
  port: 7545
};
```

instead of:

```
module.exports = [{
  rpcUrl: 'http://localhost:22000',
  port: 7545
}];
```

**Comment by edgraaff** [comment]
You were the one that asked for multiple nodes support :)

```js
module.exports = [{
  rpcUrl: 'http://localhost:22000',
  port: 7545
}, {
  rpcUrl: 'http://localhost:22001',
  port: 7546
}];
```
